apiVersion: v1
kind: Service
metadata:
  name: manufacturingenroll
spec:
  selector:
    app: manufacturingenroll
  ports:
    - protocol: TCP
      port: 8889
      targetPort: 8889
  type: LoadBalancer